INSERT INTO public.airport (name, id_country, city, iata_code) VALUES
-- UNITED STATES
('Hartsfield-Jackson Atlanta International', (SELECT id FROM country WHERE iso_code = 'US'), 'Atlanta', 'ATL'),
('Los Angeles International', (SELECT id FROM country WHERE iso_code = 'US'), 'Los Angeles', 'LAX'),
('Chicago O''Hare International', (SELECT id FROM country WHERE iso_code = 'US'), 'Chicago', 'ORD'),
('Dallas/Fort Worth International', (SELECT id FROM country WHERE iso_code = 'US'), 'Dallas', 'DFW'),
('Denver International', (SELECT id FROM country WHERE iso_code = 'US'), 'Denver', 'DEN'),
('John F. Kennedy International', (SELECT id FROM country WHERE iso_code = 'US'), 'New York', 'JFK'),
('San Francisco International', (SELECT id FROM country WHERE iso_code = 'US'), 'San Francisco', 'SFO'),
('Seattle-Tacoma International', (SELECT id FROM country WHERE iso_code = 'US'), 'Seattle', 'SEA'),
('Harry Reid International', (SELECT id FROM country WHERE iso_code = 'US'), 'Las Vegas', 'LAS'),
('Orlando International', (SELECT id FROM country WHERE iso_code = 'US'), 'Orlando', 'MCO'),
('Miami International', (SELECT id FROM country WHERE iso_code = 'US'), 'Miami', 'MIA'),
('Newark Liberty International', (SELECT id FROM country WHERE iso_code = 'US'), 'Newark', 'EWR'),
('Phoenix Sky Harbor International', (SELECT id FROM country WHERE iso_code = 'US'), 'Phoenix', 'PHX'),
('Houston George Bush Intercontinental', (SELECT id FROM country WHERE iso_code = 'US'), 'Houston', 'IAH'),
('Boston Logan International', (SELECT id FROM country WHERE iso_code = 'US'), 'Boston', 'BOS'),
('Minneapolis-Saint Paul International', (SELECT id FROM country WHERE iso_code = 'US'), 'Minneapolis', 'MSP'),
('Detroit Metropolitan', (SELECT id FROM country WHERE iso_code = 'US'), 'Detroit', 'DTW'),
('Philadelphia International', (SELECT id FROM country WHERE iso_code = 'US'), 'Philadelphia', 'PHL'),
('Salt Lake City International', (SELECT id FROM country WHERE iso_code = 'US'), 'Salt Lake City', 'SLC'),
('Washington Dulles International', (SELECT id FROM country WHERE iso_code= 'US'), 'Washington', 'IAD'),

-- CANADA
('Toronto Pearson International', (SELECT id FROM country WHERE iso_code = 'CA'), 'Toronto', 'YYZ'),
('Vancouver International', (SELECT id FROM country WHERE iso_code = 'CA'), 'Vancouver', 'YVR'),
('Aéroport International Montréal-Trudeau', (SELECT id FROM country WHERE iso_code = 'CA'), 'Montréal', 'YUL'),
('Calgary International', (SELECT id FROM country WHERE iso_code = 'CA'), 'Calgary', 'YYC'),
('Ottawa Macdonald-Cartier International', (SELECT id FROM country WHERE iso_code = 'CA'), 'Ottawa', 'YOW'),
('Edmonton International', (SELECT id FROM country WHERE iso_code = 'CA'), 'Edmonton', 'YEG'),

-- MÉXICO
('Aeropuerto Internacional Benito Juárez', (SELECT id FROM country WHERE iso_code = 'MX'), 'Ciudad de México', 'MEX'),
('Aeropuerto Internacional de Cancún', (SELECT id FROM country WHERE iso_code = 'MX'), 'Cancún', 'CUN'),
('Aeropuerto Internacional de Guadalajara', (SELECT id FROM country WHERE iso_code = 'MX'), 'Guadalajara', 'GDL'),
('Aeropuerto Internacional de Monterrey', (SELECT id FROM country WHERE iso_code = 'MX'), 'Monterrey', 'MTY'),
('Aeropuerto Internacional de Tijuana', (SELECT id FROM country WHERE iso_code = 'MX'), 'Tijuana', 'TIJ'),

-- CENTRAL AMERICA
('Aeropuerto Internacional de Tocumen', (SELECT id FROM country WHERE iso_code = 'PA'), 'Panamá', 'PTY'),
('Aeropuerto Internacional Juan Santamaría', (SELECT id FROM country WHERE iso_code = 'CR'), 'San José', 'SJO'),
('Aeropuerto Internacional San Óscar Arnulfo Romero', (SELECT id FROM country WHERE iso_code = 'SV'), 'San Salvador', 'SAL'),
('Aeropuerto Internacional La Aurora', (SELECT id FROM country WHERE iso_code = 'GT'), 'Ciudad de Guatemala', 'GUA'),
('Aeropuerto Internacional Ramón Villeda Morales', (SELECT id FROM country WHERE iso_code = 'HN'), 'San Pedro Sula', 'SAP'),
('Aeropuerto Internacional Augusto C. Sandino', (SELECT id FROM country WHERE iso_code = 'NI'), 'Managua', 'MGA'),
('Philip S.W. Goldson International', (SELECT id FROM country WHERE iso_code = 'BZ'), 'Belize City', 'BZE'),

-- CARIBBEAN
('Aeropuerto Internacional Luis Muñoz Marín', (SELECT id FROM country WHERE iso_code = 'PR'), 'San Juan', 'SJU'),
('Aeropuerto Internacional de Punta Cana', (SELECT id FROM country WHERE iso_code = 'DO'), 'Punta Cana', 'PUJ'),
('Aeropuerto Internacional Las Américas', (SELECT id FROM country WHERE iso_code = 'DO'), 'Santo Domingo', 'SDQ'),
('Aeropuerto Internacional José Martí', (SELECT id FROM country WHERE iso_code = 'CU'), 'La Habana', 'HAV'),
('Norman Manley International', (SELECT id FROM country WHERE iso_code = 'JM'), 'Kingston', 'KIN'),
('Lynden Pindling International', (SELECT id FROM country WHERE iso_code = 'BS'), 'Nassau', 'NAS'),
('Aéroport International Toussaint Louverture', (SELECT id FROM country WHERE iso_code = 'HT'), 'Port-au-Prince', 'PAP'),
('Grantley Adams International', (SELECT id FROM country WHERE iso_code = 'BB'), 'Bridgetown', 'BGI'),
('Piarco International', (SELECT id FROM country WHERE iso_code = 'TT'), 'Port of Spain', 'POS'),
('Princess Juliana International', (SELECT id FROM country WHERE iso_code = 'SX'), 'Philipsburg', 'SXM'),

-- COLOMBIA
    ('Aeropuerto Internacional El Dorado', (SELECT id FROM country WHERE iso_code = 'CO'), 'Bogotá', 'BOG'),
    ('Aeropuerto Internacional José María Córdova', (SELECT id FROM country WHERE iso_code = 'CO'), 'Medellín', 'MDE'),
    ('Aeropuerto Olaya Herrera', (SELECT id FROM country WHERE iso_code = 'CO'), 'Medellín', 'EOH'),
    ('Aeropuerto Internacional Alfonso Bonilla Aragón', (SELECT id FROM country WHERE iso_code = 'CO'), 'Cali', 'CLO'),
    ('Aeropuerto Internacional Rafael Núñez', (SELECT id FROM country WHERE iso_code = 'CO'), 'Cartagena', 'CTG'),
    ('Aeropuerto Internacional Ernesto Cortissoz', (SELECT id FROM country WHERE iso_code = 'CO'), 'Barranquilla', 'BAQ'),
    ('Aeropuerto Internacional Simón Bolívar', (SELECT id FROM country WHERE iso_code = 'CO'), 'Santa Marta', 'SMR'),
    ('Aeropuerto Internacional Matecaña', (SELECT id FROM country WHERE iso_code = 'CO'), 'Pereira', 'PEI'),
    ('Aeropuerto Internacional Palonegro', (SELECT id FROM country WHERE iso_code = 'CO'), 'Bucaramanga', 'BGA'),
    ('Aeropuerto Internacional Camilo Daza', (SELECT id FROM country WHERE iso_code = 'CO'), 'Cúcuta', 'CUC'),
    ('Aeropuerto Internacional Gustavo Rojas Pinilla', (SELECT id FROM country WHERE iso_code = 'CO'), 'San Andrés', 'ADZ'),
    ('Aeropuerto Internacional El Edén', (SELECT id FROM country WHERE iso_code = 'CO'), 'Armenia', 'AXM'),
    ('Aeropuerto Internacional Benito Salas', (SELECT id FROM country WHERE iso_code = 'CO'), 'Neiva', 'NVA'),
    ('Aeropuerto Internacional Yariguíes', (SELECT id FROM country WHERE iso_code = 'CO'), 'Barrancabermeja', 'EJA'),
    ('Aeropuerto Internacional Los Garzones', (SELECT id FROM country WHERE iso_code = 'CO'), 'Montería', 'MTR'),
    ('Aeropuerto Internacional Antonio Nariño', (SELECT id FROM country WHERE iso_code = 'CO'), 'Pasto', 'PSO'),
    ('Aeropuerto Internacional Almirante Padilla', (SELECT id FROM country WHERE iso_code = 'CO'), 'Riohacha', 'RCH'),
    ('Aeropuerto Internacional Vásquez Cobo', (SELECT id FROM country WHERE iso_code = 'CO'), 'Leticia', 'LET'),
    ('Aeropuerto Internacional Guillermo León Valencia', (SELECT id FROM country WHERE iso_code = 'CO'), 'Popayán', 'PPN'),
    ('Aeropuerto Internacional La Nubia', (SELECT id FROM country WHERE iso_code = 'CO'), 'Manizales', 'MZL'),
    ('Aeropuerto Internacional El Alcaraván', (SELECT id FROM country WHERE iso_code = 'CO'), 'Yopal', 'EYP'),
    ('Aeropuerto Internacional Vanguardia', (SELECT id FROM country WHERE iso_code = 'CO'), 'Villavicencio', 'VVC'),
    ('Aeropuerto Internacional Alfonso López Pumarejo', (SELECT id FROM country WHERE iso_code = 'CO'), 'Valledupar', 'VUP'),
    ('Aeropuerto Internacional Gerónimo de Alderete', (SELECT id FROM country WHERE iso_code = 'CO'), 'Ipiales', 'IPI'),
    ('Aeropuerto Internacional Fabio Alberto León Bentley', (SELECT id FROM country WHERE iso_code = 'CO'), 'Mitú', 'MVP'),
    ('Aeropuerto Internacional Germán Olano', (SELECT id FROM country WHERE iso_code = 'CO'), 'Puerto Carreño', 'PCR'),
-- BRASIL
('Aeroporto Internacional de São Paulo-Guarulhos', (SELECT id FROM country WHERE iso_code = 'BR'), 'Guarulhos', 'GRU'),
('Aeroporto de Congonhas', (SELECT id FROM country WHERE iso_code = 'BR'), 'São Paulo', 'CGH'),
('Aeroporto Internacional do Rio de Janeiro-Galeão', (SELECT id FROM country WHERE iso_code = 'BR'), 'Rio de Janeiro', 'GIG'),
('Aeroporto Internacional de Brasília', (SELECT id FROM country WHERE iso_code = 'BR'), 'Brasília', 'BSB'),
('Aeroporto Internacional de Belo Horizonte-Confins', (SELECT id FROM country WHERE iso_code = 'BR'), 'Belo Horizonte', 'CNF'),
('Aeroporto Internacional de Recife', (SELECT id FROM country WHERE iso_code = 'BR'), 'Recife', 'REC'),
('Aeroporto Internacional de Salvador', (SELECT id FROM country WHERE iso_code = 'BR'), 'Salvador', 'SSA'),

-- ARGENTINA
('Aeropuerto Internacional Ministro Pistarini', (SELECT id FROM country WHERE iso_code = 'AR'), 'Ezeiza', 'EZE'),
('Aeroparque Jorge Newbery', (SELECT id FROM country WHERE iso_code = 'AR'), 'Buenos Aires', 'AEP'),
('Aeropuerto Internacional Ingeniero Ambrosio Taravella', (SELECT id FROM country WHERE iso_code = 'AR'), 'Córdoba', 'COR'),
('Aeropuerto Internacional de Mendoza', (SELECT id FROM country WHERE iso_code = 'AR'), 'Mendoza', 'MDZ'),

-- PERU / CHILE / ECUADOR / OTHERS
('Aeropuerto Internacional Jorge Chávez', (SELECT id FROM country WHERE iso_code = 'PE'), 'Callao', 'LIM'),
('Aeropuerto Internacional Alejandro Velasco Astete', (SELECT id FROM country WHERE iso_code = 'PE'), 'Cusco', 'CUZ'),
('Aeropuerto Internacional Arturo Merino Benítez', (SELECT id FROM country WHERE iso_code = 'CL'), 'Santiago', 'SCL'),
('Aeropuerto Internacional de Chile Central', (SELECT id FROM country WHERE iso_code = 'CL'), 'Concepción', 'CCP'),
('Aeropuerto Internacional Mariscal Sucre', (SELECT id FROM country WHERE iso_code = 'EC'), 'Tababela', 'UIO'),
('Aeropuerto Internacional José Joaquín de Olmedo', (SELECT id FROM country WHERE iso_code = 'EC'), 'Guayaquil', 'GYE'),
('Aeropuerto Internacional Simón Bolívar', (SELECT id FROM country WHERE iso_code = 'VE'), 'Maiquetía', 'CCS'),
('Aeropuerto Internacional Viru Viru', (SELECT id FROM country WHERE iso_code = 'BO'), 'Santa Cruz de la Sierra', 'VVI'),
('Aeropuerto Internacional El Alto', (SELECT id FROM country WHERE iso_code = 'BO'), 'La Paz', 'LPB'),
('Aeropuerto Internacional Silvio Pettirossi', (SELECT id FROM country WHERE iso_code = 'PY'), 'Luque', 'ASU'),
('Aeropuerto Internacional de Carrasco', (SELECT id FROM country WHERE iso_code = 'UY'), 'Canelones', 'MVD'),
('Cheddi Jagan International', (SELECT id FROM country WHERE iso_code = 'GY'), 'Timehri', 'GEO'),
('Johan Adolf Pengel International', (SELECT id FROM country WHERE iso_code = 'SR'), 'Zanderij', 'PBM'),
('Aéroport de Cayenne-Félix Eboué', (SELECT id FROM country WHERE iso_code = 'GF'), 'Matoury', 'CAY')

ON CONFLICT (iata_code) DO NOTHING;

